# Basic Concepts

## Simple Operations
Python also carries out multiplication and division, using an asterisk to indicate multiplication and a forward slash to indicate division.
```
>>> 2 * (3 + 4)
14
>>> 10 / 2
5.0
```
Dividing by zero in Python produces an error, as no answer can be calculated.
```
>>> 11 / 0
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
ZeroDivisionError: division by zero
```
**In Python, the last line of an error message indicates the error's type.Read error messages carefully, as they often tell you how to fix a program!**
Floats are used in Python to represent numbers that aren't integers. 
```
>>> 3/4
0.75
```
Besides addition, subtraction, multiplication, and division, Python also supports exponentiation, which is the raising of one number to the power of another. This operation is performed using two asterisks.
```
>>> 2**5
32
>>> 9 ** (1/2)
3.0
```
## Quotient & Remainder
To determine the quotient and remainder of a division, use the floor division and modulo operators, respectively. 
Floor division is done using two forward slashes.The modulo operator is carried out with a percent symbol (%)
```
>>> 20 // 6
3
>>> 1.25 % 0.5
0.25
```
## Strings
If you want to use text in Python, you have to use a string. A string is created by entering text between two single or double quotation marks.
Some characters can't be directly included in a string. For instance, double quotes can't be directly included in a double quote string; Characters like these must be escaped by placing a backslash before them. Other common characters that must be escaped are newlines and backslashes. Double quotes only need to be escaped in double quote strings, and the same is true for single quote strings.
```
>>> 'Brian\'s mother: He\'s not the Messiah. He\'s a very naughty boy!'
'Brian's mother: He's not the Messiah. He's a very naughty boy!'
```
## Newlines
Python provides an easy way to avoid manually writing "\n" to escape newlines in a string. Create a string with three sets of quotes, and newlines that are created by pressing Enter are automatically escaped for you.
```
>>> """Customer: Good morning.
Owner: Good morning, Sir. Welcome to the National Cheese Emporium."""

'Customer: Good morning.\nOwner: Good morning, Sir. Welcome to the National Cheese Emporium.'
```
## Output 
In Python, you can use the print function to produce output. This displays a textual representation of something to the screen. When a string is printed, the quotes around it are not displayed.
```
>>> print("Hello\nWorld!")
Hello
World!
```
## Input 
To get input from the user in Python, you can use the intuitively named input function. 
The function prompts the user for input, and returns what they enter as a string (with the contents automatically escaped).
```
>>> input("Enter something please: ")
Enter something please: This is what\nthe user enters!

'This is what\\nthe user enters!'
```
## Concatenation
As with integers and floats, strings in Python can be added, using a process called concatenation, which can be done on any two strings. 
When concatenating strings, it doesn't matter whether they've been created with single or double quotes.
```
>>> "Spam" + 'eggs'
'Spameggs'
>>> print("First string" + ", " + "second string")
First string, second string
```
Even if your strings contain numbers, they are still added as strings rather than integers. Adding a string to a number produces an error, as even though they might look similar, they are two different entities.
```
>>> "2" + "2"
'22'
>>> 1 + '2' + 3 + '4'
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
TypeError: unsupported operand type(s) for +: 'int' and 'str'
```
## String Operations
Strings can also be multiplied by integers. This produces a repeated version of the original string. The order of the string and the integer doesn't matter, but the string usually comes first.
Strings can't be multiplied by other strings. Strings also can't be multiplied by floats, even if the floats are whole numbers.
```
>>> print("spam" * 3)
spamspamspam
>>> 4 * '2'
'2222'
>>> '17' * '87'
TypeError: can't multiply sequence by non-int of type 'str'
>>> 'pythonisfun' * 7.0
TypeError: can't multiply sequence by non-int of type 'float'
```
